### ISSUE TITLE
Issues when deploying to openshift

### ISSUE THREAD

**Issue by henyojess** [cainus/percolator#87] opened 2014-04-11 07:23 UTC
Am getting an error when deploying a percolator based server on openshift

> events.js:72
>         throw er; // Unhandled 'error' event
>               ^ Error: listen EACCES
>     at errnoException (net.js:884:11)
>     at Server._listen2 (net.js:1003:19)
>     at listen (net.js:1044:10)
>     at net.js:1118:9
>     at dns.js:72:18
>     at process._tickDomainCallback (node.js:459:13)
>     at Function.Module.runMain (module.js:499:11)
>     at startup (node.js:119:16)
>     at node.js:901:3

am taking the ip and port from environment:
- process.env.OPENSHIFT_NODEJS_IP
- process.env.OPENSHIFT_NODEJS_PORT

and use them when creating the server:

> server = new Percolator({
>             autoLink:false,
>             port:self.port,
>             ip:self.ipaddress  
>         });

**Comment by cainus** [comment] 2014-04-11 14:34
Hey @henyojess ... I don't really know anything about openshift, but that error is a general node error that means that the server can't bind to the given ip/port.  Maybe try `console.log()`ing them to see if their values make sense?  Usually this happens when you try to run on a port below 1024 (like port 80, the default http port), and you're not running as root.

**Comment by henyojess** [comment] 2014-04-11 23:39
Thanks @cainus. Openshift(PAAS from Redhat) deployment requires the server app to bind to a specific port and ipaddress provided as environment variables during runtime. I still can't get percolator to work on openshift even with just the hello world sample. I hope you can take a look into deploying sample server on openshift when you get the time.

**Comment by cainus** [comment] 2014-04-11 23:55
Well usually the problem is a port below 1024 and improper permissions... Can you `console.log()` the port and see if it's below 1024?  If so, you're either reading the environment variable incorrectly, or the problem is on their end...

**Comment by cainus** [comment] 2014-06-08 19:04
closing after 2 months with no reply

**Closed as completed by cainus** 2014-06-08 19:04 UTC
